# Generated by Django 4.0.1 on 2022-01-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encurtador',
            name='link_original',
            field=models.CharField(max_length=500),
        ),
    ]
