# Generated by Django 4.0.1 on 2022-01-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0002_alter_encurtador_link_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encurtador',
            name='link_encurtado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
