# Generated by Django 4.0.1 on 2022-01-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0003_alter_encurtador_link_encurtado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encurtador',
            name='link_original',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
